baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sergio Sanchez'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[languages]
[languages.en]
title = "Sergio Sanchez - Ingles"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.es]
title = "Sergio Sanchez - Español"
weight = 2
contentDir = "content/es"